swagger: '2.0'
info:
  title: News Summarization using freq API
  version: "0.1"
  description: An API that can summarize a news article

paths:
  /health:
    get:
      summary: Checks the health of the service
      description: Returns the health status of the service
      operationId: app.health
      responses:
        '200':
          description: Service is healthy
        '500':
          description: Service is unhealthy
  /summarize:
    post:
      summary: Entrypoint to the extractive summarization function
      operationId: app.summarize
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
        - in: formData
          name: url
          required: true
          description: The news article text to be summarized
          type: string
        - in: formData
          name: summary_length
          required: true
          description: The length of the summary
          type: number
      responses:
        '200':
          description: Summarization performed successfully
        '500':
          description: Unable to perform the summarization
